name: 'Run Cypress tests'
on: [deployment_status]
jobs:
  e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cypress E2E Tests
        uses: cypress-io/github-action@v5
        with:
          start: npm run serve
          wait-on: 'http://localhost:3000'
        env:
          CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
          CYPRESS_RETRIES: 1
      - name: Upload artifacts on failure
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          retention-days: 1
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore
